"""edit models

Revision ID: 52395268ffe8
Revises: 40d174a8fbd5
Create Date: 2024-09-08 13:55:07.844370

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52395268ffe8'
down_revision = '40d174a8fbd5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
